version: '2'
services:
  proxy:
    image: hccorigin/nginx-rc02:1.22.0
    build:
      context: .
      dockerfile: nginx1.22.0-RC02.Dockerfile
    container_name: proxy
    hostname: proxy
#    environment:
#      TZ: 'Asia/Seoul'
    volumes:
      - $PWD/conf/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf/conf.d:/etc/nginx/conf.d
      - $PWD/html:/usr/share/nginx/html
      - $PWD/log:/var/log/nginx
    ports:
      - "9080:9080"
    privileged: true
    cpu_shares: 50
    mem_limit: 2g
    memswap_limit: 2g
    networks:
      - origin_net
networks:
  origin_net:
    external: true
